### ISSUE TITLE
The documentation is not very clear

### ISSUE THREAD

**Issue by gdistasi** [MapoDan/home-assistant#2]
Hi, 
I have some doubts related to the documentation. First, it is not clear to me the all "related_climate" or "master_climate" thing.
In my case, I have a boiler (no freezing danger for it, btw) and several rooms each with a different sensor and switch... how do I set them? Each room should have a "master_climate" that refers to the boiler? That's it?

The second doubt is related to the file_restore element. I don't understand how to write the file. Would it be possible to have, or include, some examples?

Thanks.

**Comment by MapoDan** [comment]
Ciao,

I just saw this message. Next time I suggest you to open the issue on the component page (even if I'm not a super active user, but maybe someone else can help)

In any case:
- master and related one are just used to force some state. it is optional and you don't need to define them if you don't have the need. The scope is to prevent that a climate object is changing the state of heater/cooler that in that moment was managed by a second climate object. In the normal use you should not need it.
- I'm not catching your question. the file in the config folder is just a txt file with all values expected on one line comma separated. The number of values depends on the setting of the file restore entity.
At the beginning I was using it to modify the value throug input numbers and notify entities on HA interface, but it was too complex and not working well, now I have an excel file in config folder that I open through a button on HA Interface that with a macro modify the txt file.
