### ISSUE TITLE
Extension request

### ISSUE THREAD

**Issue by mreinhold21** [MapoDan/home-assistant#3]
Hello MapoDan, 
Thanks for the addon. Through the file_restore everything can be set super. 
What is still missing for me is ... 
Feater A - Superior mode
- Holiday
- HomeOffice
- default
- away
Would it perhaps be possible to swap the file_restore here. 
Example: 
If New Parameter - Status Heating Profile - AWAY 
Then file_restore = YYY.Y
If New Parameter - Heating Profile Status - Holiday 
Then file_restore = AAA.A
If New Parameter - Heating Profile Status - Standard 
Then file_restore = BBB.B

Feater B: Oberride for ...h
Override the current profile or setting for X hours and heat/cool to temp X. 
Number of hours and temperature flexible in each case. 
Would that be possible? Could you incorporate this. 
I would be pleased to receive an answer.
Thanks Moritz

**Comment by MapoDan** [comment]
you can achive it without any change in file_restore. I have it in my home.
I have one input_select to let HA have the state if I'm at home, at home working, on holidays and then created a template sensor that returns the value of the file restore entity according to the value of the input_select.

Next time open the issue on the component page, so maybe someone else may help you faster then me :)
