### ISSUE TITLE
home assistant log

### ISSUE THREAD

**Issue by ovimoc** [MapoDan/home-assistant#4]
Hi,

I have this errors on home-assistant.log 
2023-06-11 20:18:37.807 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.living_ac (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
2023-06-11 20:18:37.816 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.living_centrala (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
2023-06-11 20:18:37.818 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.sufragerie (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
2023-06-11 20:18:37.820 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.ovidiu (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
2023-06-11 20:18:37.822 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.radu (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
2023-06-11 20:18:37.824 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.teodora (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

configuration.yaml:

climate:
  - platform: programmable_thermostat
    name: Living AC
    heater:
      - switch.virtual_switch_1
    cooler:
      - switch.virtual_switch_1
    actual_temp_sensor: sensor.sonoff_10017bf8f2_temperature
    target_temp_sensor: sensor.program_temperature
    tolerance: 0.31
    hvac_options: 3

  - platform: programmable_thermostat
    name: Living Centrala
    heater:
      - switch.sonoff_1001513d86
      - switch.sonoff_100151cacc
      - switch.sonoff_100151d783
    actual_temp_sensor: sensor.sonoff_10017bf8f2_temperature
    target_temp_sensor: sensor.program_temperature
    tolerance: 0.31
    hvac_options: 3

  - platform: programmable_thermostat
    name: Ovidiu
    heater:
      - switch.sonoff_10013b70a3_3
      - switch.sonoff_100151d9c8
    cooler:
      - switch.sonoff_10013b70a3_3
      - switch.sonoff_100151d9c8
    actual_temp_sensor: sensor.sonoff_10017bfdd2_temperature
    target_temp_sensor: sensor.program_temperature
    tolerance: 0.11
    hvac_options: 3

  - platform: programmable_thermostat
    name: Teodora
    heater:
      - switch.sonoff_1001209084_1
      - switch.sonoff_100150f547
    cooler: 
      - switch.sonoff_1001209084_1
      - switch.sonoff_100150f547
    actual_temp_sensor: sensor.sonoff_10017bf483_temperature
    target_temp_sensor: sensor.program_temperature
    tolerance: 0.11
    hvac_options: 3

  - platform: programmable_thermostat
    name: Radu
    heater:
      - switch.sonoff_1001209084_4
      - switch.sonoff_1001510bdd
    cooler: 
      - switch.sonoff_1001209084_4
      - switch.sonoff_1001510bdd
    actual_temp_sensor: sensor.sonoff_10017bfe0f_temperature
    target_temp_sensor: sensor.program_temperature
    tolerance: 0.11
    hvac_options: 3

  - platform: programmable_thermostat
    name: Sufragerie
    heater: 
      - switch.sonoff_100152257b
      - switch.sonoff_10013b70a3_1
    cooler:
      - switch.sonoff_100152257b
      - switch.sonoff_10013b70a3_1
    actual_temp_sensor: sensor.sonoff_10017bf5b2_temperature
    target_temp_sensor: sensor.program_temperature
    tolerance: 0.11
    hvac_options: 3

**Comment by Mateiuc** [comment]
> Hi,
> 
> I have this errors on home-assistant.log 2023-06-11 20:18:37.807 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.living_ac (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author. 2023-06-11 20:18:37.816 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.living_centrala (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author. 2023-06-11 20:18:37.818 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.sufragerie (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author. 2023-06-11 20:18:37.820 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.ovidiu (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author. 2023-06-11 20:18:37.822 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.radu (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author. 2023-06-11 20:18:37.824 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.teodora (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
> 
> configuration.yaml:
> 
> climate:
> 
> * platform: programmable_thermostat
>   name: Living AC
>   heater:
>   
>   * switch.virtual_switch_1
>     cooler:
>   * switch.virtual_switch_1
>     actual_temp_sensor: sensor.sonoff_10017bf8f2_temperature
>     target_temp_sensor: sensor.program_temperature
>     tolerance: 0.31
>     hvac_options: 3
> * platform: programmable_thermostat
>   name: Living Centrala
>   heater:
>   
>   * switch.sonoff_1001513d86
>   * switch.sonoff_100151cacc
>   * switch.sonoff_100151d783
>     actual_temp_sensor: sensor.sonoff_10017bf8f2_temperature
>     target_temp_sensor: sensor.program_temperature
>     tolerance: 0.31
>     hvac_options: 3
> * platform: programmable_thermostat
>   name: Ovidiu
>   heater:
>   
>   * switch.sonoff_10013b70a3_3
>   * switch.sonoff_100151d9c8
>     cooler:
>   * switch.sonoff_10013b70a3_3
>   * switch.sonoff_100151d9c8
>     actual_temp_sensor: sensor.sonoff_10017bfdd2_temperature
>     target_temp_sensor: sensor.program_temperature
>     tolerance: 0.11
>     hvac_options: 3
> * platform: programmable_thermostat
>   name: Teodora
>   heater:
>   
>   * switch.sonoff_1001209084_1
>   * switch.sonoff_100150f547
>     cooler:
>   * switch.sonoff_1001209084_1
>   * switch.sonoff_100150f547
>     actual_temp_sensor: sensor.sonoff_10017bf483_temperature
>     target_temp_sensor: sensor.program_temperature
>     tolerance: 0.11
>     hvac_options: 3
> * platform: programmable_thermostat
>   name: Radu
>   heater:
>   
>   * switch.sonoff_1001209084_4
>   * switch.sonoff_1001510bdd
>     cooler:
>   * switch.sonoff_1001209084_4
>   * switch.sonoff_1001510bdd
>     actual_temp_sensor: sensor.sonoff_10017bfe0f_temperature
>     target_temp_sensor: sensor.program_temperature
>     tolerance: 0.11
>     hvac_options: 3
> * platform: programmable_thermostat
>   name: Sufragerie
>   heater:
>   
>   * switch.sonoff_100152257b
>   * switch.sonoff_10013b70a3_1
>     cooler:
>   * switch.sonoff_100152257b
>   * switch.sonoff_10013b70a3_1
>     actual_temp_sensor: sensor.sonoff_10017bf5b2_temperature
>     target_temp_sensor: sensor.program_temperature
>     tolerance: 0.11
>     hvac_options: 3

hi, how do you  fix it?

**Comment by MapoDan** [comment]
Ciao 
This wasn't an error, just a warning.
Now it is solved with version 8.3

Next time open the issue on the component page
